[package]
name = "rusty"
version = "0.1.2"
authors = ["Anandpskerala <anandps002@gmail.com>"]
edition = "2018"

[dependencies]
teloxide = "0.2.0"
futures = "0.3.4"
tokio = "0.2.13"
log = "0.4.8"
pretty_env_logger = "0.4.0"
lazy_static = "1.4.0"
dotenv = "0.15.0"
